version: "3.3"
services:

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                     P H P  v 7.4.x                                       #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#


  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                                  APACHE2  v2.4.43                        #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#


  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                       MYSQL v8 OR LATEST                                 #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#

  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    volumes:
            - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql


#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                         P H P M Y A D M I N                              #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:db
    ports:
      - "8081:80"
    volumes:
            - data:/var/lib/phpmyadmin
    networks:
      - frontend
      - backend
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    container_name: phpmyadmin


networks:
  frontend:
  backend:
volumes:
    data:
